# nginx-tls.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-tls
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nginx.example.com`)
      services:
        - name: nginx
          port: 80
  tls: # This route uses TLS
    certResolver: le # Uses our certificate resolver to get a certificate automatically!